name: "ci"

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: "always"

jobs:
    ci:
        runs-on: "ubuntu-latest"

        steps:
            - uses: "actions/checkout@v4"

            - run: "rustc --version"

            - run: "cargo build --verbose"
            - run: "cargo test --verbose"
            - run: "cargo clippy --verbose -- -D warnings"
            - run: "cargo fmt -- --check"
