name: "ci"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: "always"

jobs:
  ci:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        rust-version: ["1.74.0", "stable"]
    steps:
      - uses: "actions/checkout@v4.1.1"

      - uses: "dtolnay/rust-toolchain@master"
        with:
          toolchain: "${{ matrix.rust-version }}"
          components: "clippy, rustfmt"

      - run: "rustc --version"
      - run: "cargo build --verbose"
      - run: "cargo test --verbose"
      - run: "cargo clippy --verbose -- -D warnings"
      - run: "cargo fmt -- --check"

  lint-general:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4.1.1"

      - name: "Setup Node.js"
        uses: "actions/setup-node@v4.0.1"
        with:
          node-version: "20.x"

      - run: "npm clean-install"

      - run: 'npm run lint:commit -- --to "${{ github.sha }}"'
      - run: "npm run lint:editorconfig"
      - run: "npm run lint:markdown"
      - run: "npm run lint:prettier"
